### PR TITLE
Rename CSS file; delete COD PNGs.

### PR DESCRIPTION
**Pull request by bryce-carson**
All PNGs rendered by the server should be created in a temporary directory, and certainly not committed to the repository.

SE-banner has been renamed to spatialEpisimBanner. Explicit names are better than abbreviations.

### CODE REVIEW

**Comment by ashokkrish** [comment]
> All PNGs rendered by the server should be created in a temporary directory, and certainly not committed to the repository.

When you say temp directory will the files autodelete upon exit? What if the user wants a few random images to include in their presentation or manuscript?

**Comment by bryce-carson** [comment]
> > All PNGs rendered by the server should be created in a temporary directory, and certainly not committed to the repository.
> 
> When you say temp directory will the files autodelete upon exit? What if the user wants a few random images to include in their presentation or manuscript?

## Explanation
### Using shinyapps.io
Every session will have its own temporary directory in which images are generated on the server. If a user disconnects from the application they shouldn't expect their data to be persisted; they would need to re-run the simulation if they reconnect the application.

### Running locally
Every session will have its own temporary directory in which images are generated by the server. If a user disconnects from the application they _might_ expect their data to persist _until the restart their computer_; they would need to re-run the simulation if they restart their computer and would like to access those frames of the animation (a given PNG).

## Explain clause in commit message
It's not meaningful to the software, spatialEpisim, to have some of any of the generated PNGs committed; whomever committed them shouldn't have. When the software is completed,

> All PNGs rendered by the server should be created in a temporary directory

For now they'll be dumped into a sub-directory of the project folder (the "installation directory"); _this remote copy_ of the software, which is not installed on anyone's computer, doesn't run simulations, and is just a code repository, doesn't need a copy of that PNG data. That's why I removed the files.

**Comment by ashokkrish** [comment]
> ### Running locally
> Every session will have its own temporary directory in which images are generated by the server. If a user disconnects from the application they _might_ expect their data to persist _until the restart their computer_; they would need to re-run the simulation if they restart their computer and would like to access those frames of the animation (a given PNG).

My workshop attendees will all run locally and I want them to be able to see the generated PNGs easily. For example, they may want to see the disease spread map for the 87th, 102nd and 121st days of the simulation. Please make sure the PNGs do indeed get saved locally somewhere.

I agree to the point that these images need not be present as a part of the GitHub repository.

**Comment by ashokkrish** [comment]
> > ### Running locally
> > Every session will have its own temporary directory in which images are generated by the server. If a user disconnects from the application they _might_ expect their data to persist _until the restart their computer_; they would need to re-run the simulation if they restart their computer and would like to access those frames of the animation (a given PNG).
> 
> My workshop attendees will all run locally and I want them to be able to see the generated PNGs easily. For example, they may want to see the disease spread map for the 87th, 102nd and 121st days of the simulation. Please make sure the PNGs do indeed get saved locally somewhere.
> 
> I agree to the point that these images need not be present as a part of the GitHub repository.

Also there is a directly called Past Sims inside www directory. You can remove them as well.

**Comment by bryce-carson** [comment]
> there is a directly called Past Sims inside www directory. You can remove them as well.

I meant to ask about that. Thanks.

**Comment by bryce-carson** [comment]
> > ### Running locally
> > Every session will have its own temporary directory in which images are generated by the server. If a user disconnects from the application they _might_ expect their data to persist _until the restart their computer_; they would need to re-run the simulation if they restart their computer and would like to access those frames of the animation (a given PNG).
> 
> My workshop attendees will all run locally and I want them to be able to see the generated PNGs easily. For example, they may want to see the disease spread map for the 87th, 102nd and 121st days of the simulation. Please make sure the PNGs do indeed get saved locally somewhere.
> 
> I agree to the point that these images need not be present as a part of the GitHub repository.
> 
> 

When a user downloads the software and runs it, the image files will still be created in the MP4 directory as has been done. This commit only removed the files which were committed to the repository.

As a *planner change*, the images will be even more readily available than before with the video (I plan to use a slideshow instead, which will give control of the rate of change between slides to the user, directly in the app; ergo, no fussing about with choosing a good default for how long the video is and how rapidly it should display points in time).

**Pull request merged**
